### ISSUE TITLE
Particles.js occasionally doesn't run

### ISSUE THREAD

**Issue by bradley-r** [bradley-r/landing-page#2]
Might be due to specialist in-browser security or 5K res, but sometimes the background will just be #393939 with no overlaid particles. Clearing cache and refreshing multiple times fixes this.

**Comment by bradley-r** [comment]
Error caught:

`Uncaught ReferenceError: particlesJS is not definedat app.js:14`

**Comment by jackputtockk** [comment]
particles.js Issue Fixed - "Uncaught ReferenceError: particlesJS is not definedat app.js:14"

---
Jack Puttock,
jackputtock.com
Front End Web Developer
